### ISSUE TITLE
Secon fails

### ISSUE THREAD

**Issue by pmjordan** [tmforum-oda/oda-canvas-charts#24]
## Long story short

My deployment of the chart fails; kubectl reports a repeating restart and error backoff for the secon container. 

## Description

<details><summary>start minikube and install canvas</summary>

Deploying on an Azure VM centos 8 withi mninikube. My minikube instance is started with
`minikube start --addons registry ingress --insecure-registry "10.0.0.0/8","192.168.0.0/16"`

I then install canvas using the script
`./install_canvas.sh`
</details>

<details><summary>kubectl reports canvas is unavailable</summary>
Then kubectl reports that canvas is unavailable
`kubectl get deployment`

NAME                     READY   UP-TO-DATE   AVAILABLE   AGE
canvas-keycloak          1/1     1            1           5s
oda-controller-ingress   0/1     1            0           5s

`kubectl get pods`
NAME                                      READY   STATUS     RESTARTS   AGE
canvas-keycloak-7874b487c9-bf5nj          0/1     Error      1          57s
oda-controller-ingress-85689ccbd6-4zfg2   1/2     NotReady   3          57s

`kubectl describe pod oda-controller-ingress-85689ccbd6-4zfg2
Name:         oda-controller-ingress-85689ccbd6-4zfg2
Namespace:    default
Priority:     0
Node:         minikube/192.168.49.2
Start Time:   Thu, 24 Jun 2021 14:44:22 +0000
Labels:       app=oda-controller-ingress
              app.kubernetes.io/instance=canvas
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=controller
              helm.sh/chart=controller-0.1.0
              pod-template-hash=85689ccbd6
Annotations:  <none>
Status:       Running
IP:           172.17.0.6
IPs:
  IP:           172.17.0.6
Controlled By:  ReplicaSet/oda-controller-ingress-85689ccbd6
Containers:
  oda-controller-ingress:
    Container ID:   docker://0e196964003ef2b4a9aa6ad7233d2dd99fc83e9d3112c83f45eebab93d39927a
    Image:          tmforumodacanvas/component-controller:master
    Image ID:       docker-pullable://tmforumodacanvas/component-controller@sha256:bc5ecb5626b26eee3abbdb589288a6c48a3153bf9025acf4df1365642e4313d3
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Thu, 24 Jun 2021 14:44:24 +0000
    Ready:          True
    Restart Count:  0
    Environment Variables from:
      canvas-configmap  ConfigMap  Optional: false
      canvas-secret     Secret     Optional: false
    Environment:        <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from odacomponent-account-token-46rsb (ro)
  seccon:
    Container ID:   docker://e6342cc89416c7178e55777a8fd0bda20881bf696c23396a3863195e6d25bc4b
    Image:          tmforumodacanvas/security-listener:master
    Image ID:       docker-pullable://tmforumodacanvas/security-listener@sha256:d686f44b910558ba2432856f9e2e4e12c9fdf8330f15df41ee28815073feee71
    Port:           5000/TCP
    Host Port:      0/TCP
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 24 Jun 2021 14:46:04 +0000
      Finished:     Thu, 24 Jun 2021 14:46:04 +0000
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 24 Jun 2021 14:45:12 +0000
      Finished:     Thu, 24 Jun 2021 14:45:12 +0000
    Ready:          False
    Restart Count:  4
    Environment Variables from:
      canvas-configmap  ConfigMap  Optional: false
      canvas-secret     Secret     Optional: false
    Environment:        <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from odacomponent-account-token-46rsb (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  odacomponent-account-token-46rsb:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  odacomponent-account-token-46rsb
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                 From               Message
  ----     ------     ----                ----               -------
  Normal   Scheduled  104s                default-scheduler  Successfully assigned default/oda-controller-ingress-85689ccbd6-4zfg2 to minikube
  Normal   Pulling    103s                kubelet            Pulling image "tmforumodacanvas/component-controller:master"
  Normal   Pulled     102s                kubelet            Successfully pulled image "tmforumodacanvas/component-controller:master" in 1.104600265s
  Normal   Created    102s                kubelet            Created container oda-controller-ingress
  Normal   Started    102s                kubelet            Started container oda-controller-ingress
  Normal   Pulled     101s                kubelet            Successfully pulled image "tmforumodacanvas/security-listener:master" in 1.051713286s
  Normal   Pulled     99s                 kubelet            Successfully pulled image "tmforumodacanvas/security-listener:master" in 1.074514777s
  Normal   Pulled     81s                 kubelet            Successfully pulled image "tmforumodacanvas/security-listener:master" in 1.030029787s
  Warning  BackOff    68s (x5 over 98s)   kubelet            Back-off restarting failed container
  Normal   Pulling    55s (x4 over 102s)  kubelet            Pulling image "tmforumodacanvas/security-listener:master"
  Normal   Created    54s (x4 over 101s)  kubelet            Created container seccon
  Normal   Started    54s (x4 over 100s)  kubelet            Started container seccon
  Normal   Pulled     54s                 kubelet            Successfully pulled image "tmforumodacanvas/security-listener:master" in 1.06064275s`</details>

<details><summary>Counter example</summary>
If I comment out the seccon container from the template, 

 spec:
      serviceAccountName: odacomponent-account
      containers:
      - name: oda-controller-ingress
        image: {{.Values.deployment.compconimage}}
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-configmap
          - secretRef:
              name: {{ .Release.Name }}-secret
        #      - name: seccon
        #        image: {{.Values.deployment.secconimage}}
        #        imagePullPolicy: Always
        #        envFrom:
        #          - configMapRef:
        #              name: {{ .Release.Name }}-configmap
        #          - secretRef:
        #              name: {{ .Release.Name }}-secret
        #        ports:
        #        - name: seccon
        #          containerPort: 5000

then kubectl reports a running deployment of canvas as expected

`$ kubectl get deployment`
NAME                     READY   UP-TO-DATE   AVAILABLE   AGE
canvas-keycloak          1/1     1            1           31s
oda-controller-ingress   1/1     1            1           31s

</details>

## Environment

kopf --version
-bash: kopf: command not found
$ pip show kopf
-bash: pip: command not found
 kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"132a687512d7fb058d0f5890f07d4121b3f0a2e2", GitTreeState:"clean", BuildDate:"2021-05-12T12:32:49Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
$ python --version
-bash: python: command not found
$ python3 --version
Python 3.6.8
</details>

cat /etc/os-release file
NAME="CentOS Linux"
VERSION="8 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="8"

**Comment by brian-burton** [comment]
@pmjordan #23 should fix this. Let me finish merging conflicts and I'll ask you to test again when that's done.

**Comment by pmjordan** [comment]
Sorry to report that this issue has not been fixed

**Comment by brian-burton** [comment]
Hi @pmjordan , can you try installing using the updated instructions in the README on the main repo page, please? There's a different install script for the default installation. I was able to replicate your issue with the original installation script, but the instructions (and the code in the security controller and security listener) have changed. I haven't removed the original installation script because it should work once we've got the service mesh installation configured correctly but for now please use the `install_cert-manager.sh` script as per the new README and we'll reopen this issue if you're still seeing the same problem.

**Comment by pmjordan** [comment]
You are correct, I had not used the new install instructions but now that I have done so I still see a problem:

kubectl get pods -A
NAMESPACE      NAME                                       READY   STATUS              RESTARTS   AGE
canvas         canvas-keycloak-7d4f9f776-pkbfs            0/1     Error               6          20m
canvas         compcrdwebhook-cc7795878-bnxsq             0/1     ContainerCreating   0          20m
canvas         oda-controller-ingress-68c9765895-8jgs8    2/2     Running             0          20m
cert-manager   cert-manager-5d7f97b46d-t4zmn              1/1     Running             0          22m
cert-manager   cert-manager-cainjector-69d885bf55-crkrq   1/1     Running             0          22m
cert-manager   cert-manager-webhook-54754dcdfd-cx2hp      1/1     Running             0          22m
kube-system    coredns-558bd4d5db-d98b4                   1/1     Running             0          25m
kube-system    etcd-minikube                              1/1     Running             0          25m
kube-system    kube-apiserver-minikube                    1/1     Running             0          25m
kube-system    kube-controller-manager-minikube           1/1     Running             0          25m
kube-system    kube-proxy-np7ld                           1/1     Running             0          25m
kube-system    kube-scheduler-minikube                    1/1     Running             0          25m
kube-system    registry-mhltv                             1/1     Running             0          25m
kube-system    registry-proxy-whbhq                       1/1     Running             0          25m
kube-system    storage-provisioner                        1/1     Running             0          25m




kubectl describe pod compcrdwebhook-cc7795878-bnxsq -n canvas
Name:           compcrdwebhook-cc7795878-bnxsq
Namespace:      canvas
Priority:       0
Node:           minikube/192.168.49.2
Start Time:     Mon, 02 Aug 2021 21:47:53 +0100
Labels:         app=compcrdwebhook




kubectl describe pod canvas-keycloak-7d4f9f776-pkbfs -n canvas
Name:         canvas-keycloak-7d4f9f776-pkbfs
Namespace:    canvas
Priority:     0
Node:         minikube/192.168.49.2
Start Time:   Mon, 02 Aug 2021 21:47:53 +0100
Labels:       app=canvas-keycloak
              app.kubernetes.io/instance=canvas
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=keycloak
              app.kubernetes.io/version=12.0.3
              helm.sh/chart=keycloak-0.3.0
              pod-template-hash=7d4f9f776
Annotations:  <none>
Status:       Running
IP:           172.17.0.8
IPs:
  IP:           172.17.0.8
Controlled By:  ReplicaSet/canvas-keycloak-7d4f9f776
Containers:
  keycloak:
    Container ID:   docker://276862fad588d510fafe387126d90212c01d4adce3a94e1a23e8b64fcecdc489
    Image:          quay.io/keycloak/keycloak:12.0.3
    Image ID:       docker-pullable://quay.io/keycloak/keycloak@sha256:b2b760cceb97fe4f360fb89e43b9ebe0ba39faafb33f04507fa9f1c49e7ca749
    Ports:          8080/TCP, 8443/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Mon, 02 Aug 2021 22:06:53 +0100
      Finished:     Mon, 02 Aug 2021 22:07:46 +0100
    Ready:          False
    Restart Count:  6
    Environment Variables from:
      canvas-kc-configmap  ConfigMap  Optional: false
      canvas-secret        Secret     Optional: false
    Environment:
      PROXY_ADDRESS_FORWARDING:  true
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-2pmbc (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  kube-api-access-2pmbc:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  20m                  default-scheduler  Successfully assigned canvas/canvas-keycloak-7d4f9f776-pkbfs to minikube
  Warning  Failed     18m                  kubelet            Failed to pull image "quay.io/keycloak/keycloak:12.0.3": rpc error: code = Unknown desc = context canceled
  Warning  Failed     18m                  kubelet            Error: ErrImagePull
  Normal   BackOff    18m                  kubelet            Back-off pulling image "quay.io/keycloak/keycloak:12.0.3"
  Warning  Failed     18m                  kubelet            Error: ImagePullBackOff
  Normal   Pulling    18m (x2 over 20m)    kubelet            Pulling image "quay.io/keycloak/keycloak:12.0.3"
  Normal   Pulled     13m                  kubelet            Successfully pulled image "quay.io/keycloak/keycloak:12.0.3" in 5m37.623356514s
  Normal   Started    9m29s (x4 over 12m)  kubelet            Started container keycloak
  Normal   Pulled     7m46s (x4 over 11m)  kubelet            Container image "quay.io/keycloak/keycloak:12.0.3" already present on machine
  Normal   Created    7m44s (x5 over 12m)  kubelet            Created container keycloak
  Warning  BackOff    37s (x29 over 11m)   kubelet            Back-off restarting failed container
                app.kubernetes.io/instance=canvas
                app.kubernetes.io/managed-by=Helm
                app.kubernetes.io/name=webhook
                app.kubernetes.io/version=0.0.1
                helm.sh/chart=webhook-0.0.1
                pod-template-hash=cc7795878
Annotations:    <none>
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  ReplicaSet/compcrdwebhook-cc7795878
Containers:
  compcrdwebhook:
    Container ID:   
    Image:          tmforumodacanvas/compcrdwebhook:0.3
    Image ID:       
    Port:           8443/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /etc/secret-volume from secret-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-pfqc5 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  secret-volume:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  compcrdwebhook-secret
    Optional:    false
  kube-api-access-pfqc5:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason       Age                  From               Message
  ----     ------       ----                 ----               -------
  Normal   Scheduled    17m                  default-scheduler  Successfully assigned canvas/compcrdwebhook-cc7795878-bnxsq to minikube
  Warning  FailedMount  8m56s (x3 over 13m)  kubelet            Unable to attach or mount volumes: unmounted volumes=[secret-volume], unattached volumes=[secret-volume kube-api-access-pfqc5]: timed out waiting for the condition
  Warning  FailedMount  2m9s (x4 over 15m)   kubelet            Unable to attach or mount volumes: unmounted volumes=[secret-volume], unattached volumes=[kube-api-access-pfqc5 secret-volume]: timed out waiting for the condition
  Warning  FailedMount  86s (x16 over 17m)   kubelet            MountVolume.SetUp failed for volume "secret-volume" : secret "compcrdwebhook-secret" not found
